[app_servers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[app_servers:vars]
app_name=netflix-catalog
app_user=devops
app_port=8001
app_env=production
log_dir=/var/log/devops-netflix
config_dir=/etc/devops-netflix
