[app_servers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[app_servers:vars]
app_name=amazon-services
app_user=devops
app_env=production
log_dir=/var/log/devops-amazon
config_dir=/etc/devops-amazon
